### ISSUE TITLE
Introspect raised exception on docker.io/docker

### ISSUE THREAD

**Issue by amitkrout** [navidshaikh/introspection#17]
While running introspect on docker "introspect docker.io/docker" throws exception `introexceptions.CannotCreateContainer(msg)`

```
$ introspect docker.io/docker
Traceback (most recent call last):
  File "/usr/bin/introspect", line 123, in <module>
    main()
  File "/usr/bin/introspect", line 117, in main
    tester.run()
  File "/usr/lib/python2.7/site-packages/Introspection/test_runner.py", line 339, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/Introspection/test_runner.py", line 225, in _run
    self.run_image_tests()
  File "/usr/lib/python2.7/site-packages/Introspection/test_runner.py", line 202, in run_image_tests
    self.containerutils.create_container(params)
  File "/usr/lib/python2.7/site-packages/Introspection/utils.py", line 181, in create_container
    return self.docker.create_container(params)
  File "/usr/lib/python2.7/site-packages/Introspection/dockerutils.py", line 144, in create_container
    raise introexceptions.CannotCreateContainer(msg)
Introspection.introexceptions.CannotCreateContainer: Can not create container.Command used: ['/usr/bin/docker', 'run', '--user', 'root', '-v', '/tmp/tmpiaNjy9:/var/tmp/container_introspection/:Z', '--entrypoint', '/var/tmp/container_introspection/introspection_script.sh', '--name', 'cert_asouod', 'docker.io/docker']
Error:no such file or directory
Error response from daemon: Cannot start container 1d029536f52dd60a120cbe539781775dba7572f33d35ff3ff1de1d23d1c07448: [8] System error: no such file or directory
```

**Comment by navidshaikh** [comment]
Was the image `docker.io/docker` available (docker pull-ed beforehand) while this test ran?
