### ISSUE TITLE
python introspect ... errors out

### ISSUE THREAD

**Issue by concaf** [navidshaikh/introspection#6]
I followed the README as it is, and the following error occurs -

(I am running as root)

``` bash

# python introspect busybox --offline
Traceback (most recent call last):
  File "introspect", line 118, in <module>
    main()
  File "introspect", line 113, in main
    tester.run()
  File "/root/introspection/introspection/probe_runner.py", line 326, in run
    self._run()
  File "/root/introspection/introspection/probe_runner.py", line 215, in _run
    self.run_image_tests()
  File "/root/introspection/introspection/probe_runner.py", line 195, in run_image_tests
    self.containerutils.create_container(params)
  File "/root/introspection/introspection/utils.py", line 181, in create_container
    return self.docker.create_container(params)
  File "/root/introspection/introspection/dockerutils.py", line 144, in create_container
    raise introexceptions.CTSCannotCreateContainer(msg)
introspection.introexceptions.CTSCannotCreateContainer: Can not create container.Command used: ['/usr/bin/docker', 'run', '--user', 'root', '-v', '/tmp/tmp06vF2n:/var/tmp/container_introspection/', '--entrypoint', '/var/tmp/container_introspection/introspection_script.sh', '--name', 'cert_ujorqx', 'busybox']
Error:/usr/bin/docker: Error response from daemon: Container command '/var/tmp/container_introspection/introspection_script.sh' not found or does not exist..

```

**Comment by concaf** [comment]
Oh wait, the tool works fine with `# python introspect centos --offline`.
Something wrong with `busybox`.

**Comment by navidshaikh** [comment]
@containscafeine : the `busybox` image does not have all the utilities required for data collections scripts to be executed.
There should be a check in the scripts to identify if all the utilities required for introspection to work is present in the image or not and display meaningful error message otherwise.

**Comment by navidshaikh** [comment]
Closing the issue with another issue mentioning exact reason for traceback https://github.com/navidshaikh/introspection/issues/7
