### ISSUE TITLE
Missing test file from the package installation

### ISSUE THREAD

**Issue by navidshaikh** [navidshaikh/introspection#9]
@dharmit found this while testing the 0.1 release

```
$ introspect docker.io/centos:centos7
Traceback (most recent call last):
  File "/usr/bin/introspect", line 123, in <module>
    main()
  File "/usr/bin/introspect", line 117, in main
    tester.run()
  File "/usr/lib/python2.7/site-packages/Introspection/test_runner.py", line 338, in run
    self.pre_test_run_setup()
  File "/usr/lib/python2.7/site-packages/Introspection/test_runner.py", line 217, in pre_test_run_setup
    self.copy_scripts_in_test_dir()
  File "/usr/lib/python2.7/site-packages/Introspection/test_runner.py", line 136, in copy_scripts_in_test_dir
    for script in self.test_scripts_source_path()]
  File "/usr/lib64/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/Introspection/rpm_verify_tests.py'

$ ls /usr/lib/python2.7/site-packages/Introspection
constants.py     __init__.py        introexceptions.py   package_tests.py           selinux_tests.py   utils.py
constants.pyc    __init__.pyc       introexceptions.pyc  package_tests.pyc          selinux_tests.pyc  utils.pyc
dockerutils.py   inspect_tests.py   metadata.py          selinux_denials_tests.py   test_runner.py
dockerutils.pyc  inspect_tests.pyc  metadata.pyc         selinux_denials_tests.pyc  test_runner.pyc
```

**Comment by navidshaikh** [comment]
`rpm_verify_tests.py` python file was missing from the git repository and thus installation.
